export const courses = [
  { slug: 'windows-admin', title: 'Windows Admin Career Program', short: 'Windows Admin', duration: '2.5 Months', badge: 'Beginner Friendly', description: 'An entry-level IT infrastructure program built for practical job readiness — perfect for freshers starting their IT career.', why: ['Quick entry to IT roles in 2.5 months', 'No prior IT experience required', 'Hands-on Windows Server labs'], about: 'A foundation-level IT infrastructure course designed for absolute beginners. Learn how businesses set up, secure and manage their computer systems day to day.', learn: ['A+ Fundamentals', 'N+ Networking', 'Windows Server Admin', 'Microsoft 365', 'System Security Basics', 'IT Helpdesk Practices'], roles: ['IT Support Executive', 'Junior System Administrator', 'Helpdesk / Technical Associate'] },
  { slug: 'networking-system-admin', title: 'Networking & System Admin Program', short: 'Networking & System Admin', duration: '4.5 Months', badge: 'CCNA-Aligned Curriculum', description: 'A practical networking and system administration track for candidates aiming for stronger IT fresher opportunities.', why: ['CCNA 200-301 aligned, with real lab practice', 'Windows Server administration and monitoring tools', 'Placement support with interview preparation'], about: 'Train to design, configure and troubleshoot the networks and servers that connect every modern organisation. Build a strong foundation in routing, switching and system administration.', learn: ['CCNA 200-301', 'Windows Server Admin', 'Monitoring Tools', 'Microsoft 365', 'Network Troubleshooting', 'Security Fundamentals'], roles: ['Network Support Engineer', 'System Administrator', 'NOC / Monitoring Associate'] },
  { slug: 'networking-ceh-cloud', title: 'Master Networking & CEH / Cloud', short: 'Networking, CEH & Cloud', duration: '7–8 Months', badge: 'CEH + Cloud (AWS)', description: 'An advanced infrastructure career track for IT graduates targeting networking, cyber security, cloud and support-engineer roles.', why: ['CCNA, Linux, CEH + VAPT and AWS in one track', 'Real penetration-testing and cloud lab environments', 'Flexible evening and weekend batches'], about: 'Our most advanced infrastructure track combines enterprise networking, Linux administration, ethical hacking and AWS cloud computing into one career-focused programme.', learn: ['CCNA 200-301', 'Linux Basics', 'CEH + VAPT', 'Cloud (AWS)', 'Network Security', 'Security Auditing'], roles: ['Cybersecurity Analyst', 'Cloud Support Engineer', 'Senior Network Engineer'] },
  { slug: 'data-science-ai', title: 'Data Scientist with AI Program', short: 'Data Scientist with AI', duration: '6–7 Months', badge: 'Python, Power BI & ML', description: 'A data and AI career track for IT graduates who want practical skills for analytics, reporting and entry-level data roles.', why: ['10+ industry data projects for your portfolio', 'Python, Power BI, Machine Learning and NLP', 'Dedicated support for data and AI roles'], about: 'Move from data fundamentals to applied machine learning and AI, with real datasets and projects that show you can solve business problems with data.', learn: ['Python', 'Power BI', 'Machine Learning', 'NLP', 'SQL & Data Handling', 'Applied AI Tools'], roles: ['Data Analyst', 'Power BI / SQL Analyst', 'Junior Data Scientist'] },
  { slug: 'ai-ml-advanced', title: 'AI / ML Advanced Program', short: 'AI / ML Advanced', duration: '8–9 Months', badge: 'Deep Learning & GenAI', description: 'Our deepest AI/ML program — covering machine learning, generative AI and deployment concepts for advanced, future-ready roles.', why: ['Generative AI, RAG and Agentic AI in depth', 'Build, fine-tune and deploy AI model projects', 'Designed for advanced AI/ML career roles'], about: 'Go beyond data science into deep learning, generative AI and deployment techniques used in today’s most in-demand AI roles.', learn: ['Deep Learning', 'Generative AI', 'RAG & Agentic AI', 'API Deployment', 'Python for AI', 'Model Evaluation'], roles: ['Machine Learning Engineer', 'AI Engineer', 'AI Deployment Specialist'] },
  { slug: 'full-stack-developer', title: 'Full Stack Developer MERN / Java', short: 'Full Stack Developer', duration: '6 Months', badge: 'MERN & Java Stack', description: 'A full stack developer career track for IT graduates targeting software developer, web developer and entry-level coding roles.', why: ['Build real projects across React, Node/Java and databases', 'MERN and Java backend development tracks', 'Portfolio-ready projects for developer job applications'], about: 'Build complete, real-world web applications — from front-end interfaces to back-end logic and databases — using the MERN stack and Java.', learn: ['React.js', 'Node.js / Java', 'Spring Boot', 'MongoDB / MySQL', 'Git & Version Control', 'Deployment'], roles: ['Full Stack Developer', 'Web Developer', 'Junior Software Engineer'] }
];

export const courseBySlug = Object.fromEntries(courses.map((course) => [course.slug, course]));
